version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '14:00'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '14:00'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/examples/nodejs'
    schedule:
      interval: monthly
      time: '14:00'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
